name: Rust

on:
   workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  prepare:

    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.ver.outputs.version }}
    steps:
      - name: 计算版本号
        id: ver
        run: |
          VERSION="v-${GITHUB_SHA::7}"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "版本号: $VERSION"
  build:

    runs-on: windows-2025-vs2026

    steps:
    - name: get version
      id: ver
      shell: pwsh
      run: |
       $short = $env:GITHUB_SHA.Substring(0,7)
       $version = "v-$short"
       "version=$version" >> $env:GITHUB_OUTPUT
       Write-Host "the version: $version"
    - uses: actions/checkout@v4
    #- run: rustup target add x86_64-pc-windows-msvc
    - name: build binary
      run: cargo run --target x86_64-pc-windows-msvc -r -- -1
    - name: show result
      shell: bash
      run: ls -lh
    - name: make release
      run: mkdir release
    - name: build zip
      shell: bash
      run: 7z a -tzip -mx=9 release/windows_rs_feature-${{ needs.prepare.outputs.version }}.zip *.html *.json
    - name: upload
      uses: actions/upload-artifact@v4
      with:
          name: release-assest
          path: release/*.zip

  release:
    needs: build
    runs-on: windows-2025-vs2026
    permissions:
      contents: write
    steps:
    - name: fetch package
      uses: actions/download-artifact@v4
      with:
        name: release-assest
        path: release
    - uses: actions/checkout@v4
    - name: do release
      run: gh release create "${{ needs.prepare.outputs.version }}" release/*.zip --title "Release ${{ needs.prepare.outputs.version }}" --generate-notes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
