name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-2025-vs2026

    steps:
    - uses: actions/checkout@v4
    - run: rustup target add x86_64-pc-windows-msvc
    - name: build binary
      run: cargo r --target x86_64-pc-windows-msvc -r 0

